name: deploy

on:
  push:
    branches:
      - main

  jobs:
    deploy:
      runs-on: windows-latest
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '18.x'
        - name: Build web-app
          run: 
            npm ci
            npm run build
        - name: Deploy to gh-pages
            env:
              GITHUB_SHA: ${{GITHUB_SHA}}
            run: tar -czf "${{GITHUB_SHA}}".tar.gz build
        - name: Storing artifact
          uses: actions/upload-artifact@v2
          with:
            name: app-build
            path: ${{ github.sha }}.tar.gz